// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: likes.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoLikeParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetAccount  string `protobuf:"bytes,1,opt,name=TargetAccount,proto3" json:"TargetAccount,omitempty"`
	CurrentAccount string `protobuf:"bytes,2,opt,name=CurrentAccount,proto3" json:"CurrentAccount,omitempty"`
}

func (x *DoLikeParams) Reset() {
	*x = DoLikeParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_likes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoLikeParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoLikeParams) ProtoMessage() {}

func (x *DoLikeParams) ProtoReflect() protoreflect.Message {
	mi := &file_likes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoLikeParams.ProtoReflect.Descriptor instead.
func (*DoLikeParams) Descriptor() ([]byte, []int) {
	return file_likes_proto_rawDescGZIP(), []int{0}
}

func (x *DoLikeParams) GetTargetAccount() string {
	if x != nil {
		return x.TargetAccount
	}
	return ""
}

func (x *DoLikeParams) GetCurrentAccount() string {
	if x != nil {
		return x.CurrentAccount
	}
	return ""
}

type GetLikeCountParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetAccount string `protobuf:"bytes,1,opt,name=TargetAccount,proto3" json:"TargetAccount,omitempty"`
}

func (x *GetLikeCountParams) Reset() {
	*x = GetLikeCountParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_likes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLikeCountParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeCountParams) ProtoMessage() {}

func (x *GetLikeCountParams) ProtoReflect() protoreflect.Message {
	mi := &file_likes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeCountParams.ProtoReflect.Descriptor instead.
func (*GetLikeCountParams) Descriptor() ([]byte, []int) {
	return file_likes_proto_rawDescGZIP(), []int{1}
}

func (x *GetLikeCountParams) GetTargetAccount() string {
	if x != nil {
		return x.TargetAccount
	}
	return ""
}

type GetLikeCountReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Likes int64 `protobuf:"varint,1,opt,name=likes,proto3" json:"likes,omitempty"`
}

func (x *GetLikeCountReply) Reset() {
	*x = GetLikeCountReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_likes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLikeCountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeCountReply) ProtoMessage() {}

func (x *GetLikeCountReply) ProtoReflect() protoreflect.Message {
	mi := &file_likes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeCountReply.ProtoReflect.Descriptor instead.
func (*GetLikeCountReply) Descriptor() ([]byte, []int) {
	return file_likes_proto_rawDescGZIP(), []int{2}
}

func (x *GetLikeCountReply) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

var File_likes_proto protoreflect.FileDescriptor

var file_likes_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c,
	0x69, 0x6b, 0x65, 0x73, 0x22, 0x5c, 0x0a, 0x0c, 0x44, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x3a, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x29,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x32, 0x89, 0x01, 0x0a, 0x05, 0x4c, 0x69,
	0x6b, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x06, 0x64, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x13, 0x2e,
	0x6c, 0x69, 0x6b, 0x65, 0x73, 0x2e, 0x44, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x1a, 0x18, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69,
	0x6b, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x45,
	0x0a, 0x0c, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x19,
	0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x18, 0x2e, 0x6c, 0x69, 0x6b, 0x65,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x67, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x73,
	0x2f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_likes_proto_rawDescOnce sync.Once
	file_likes_proto_rawDescData = file_likes_proto_rawDesc
)

func file_likes_proto_rawDescGZIP() []byte {
	file_likes_proto_rawDescOnce.Do(func() {
		file_likes_proto_rawDescData = protoimpl.X.CompressGZIP(file_likes_proto_rawDescData)
	})
	return file_likes_proto_rawDescData
}

var file_likes_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_likes_proto_goTypes = []interface{}{
	(*DoLikeParams)(nil),       // 0: likes.DoLikeParams
	(*GetLikeCountParams)(nil), // 1: likes.GetLikeCountParams
	(*GetLikeCountReply)(nil),  // 2: likes.GetLikeCountReply
}
var file_likes_proto_depIdxs = []int32{
	0, // 0: likes.Likes.doLike:input_type -> likes.DoLikeParams
	1, // 1: likes.Likes.getLikeCount:input_type -> likes.GetLikeCountParams
	2, // 2: likes.Likes.doLike:output_type -> likes.GetLikeCountReply
	2, // 3: likes.Likes.getLikeCount:output_type -> likes.GetLikeCountReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_likes_proto_init() }
func file_likes_proto_init() {
	if File_likes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_likes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoLikeParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_likes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLikeCountParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_likes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLikeCountReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_likes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_likes_proto_goTypes,
		DependencyIndexes: file_likes_proto_depIdxs,
		MessageInfos:      file_likes_proto_msgTypes,
	}.Build()
	File_likes_proto = out.File
	file_likes_proto_rawDesc = nil
	file_likes_proto_goTypes = nil
	file_likes_proto_depIdxs = nil
}
